### ISSUE TITLE
Plugin not working....

### ISSUE THREAD

**Issue by collegeimprovements** [rhysd/vim-textobj-ruby#3]
I've installed the plugin with Neobundle.
Here are the lines from my vimrc.
 
```viml
 NeoBundle 'kana/vim-textobj-user'
 NeoBundle 'rhysd/vim-textobj-ruby'
```

I haven't added any other thing related to both of the plugins.
Am I missing something ?

**Comment by rhysd** [comment]
Could you tell me the detailed behavior when you enter `vir` or `var`?

**Comment by collegeimprovements** [comment]
Sorry, My Bad.
I was trying it on the following code and hence got confused.
```ruby
greeter = Proc.new do |name|
  puts "Hello #{name}"
end
```
It's working fine as described in README file.

----

One more thing,
I add `let g:textobj_ruby_more_mappings = 1` to my `.vimrc`
But how to use the following commands in my workflow ?
Everytime I try `ro` or any command that begins with `r` it changes the current character.
Sorry for the trouble. Thanks for this awesome plugin.

<table>
    <tr>
        <th>Description</th>
        <th>Blocks</th>
        <th>Operator-pending Mappings</th>
    </tr>
    <tr>
        <td>definitions blocks</td>
        <td>module, class, def</td>
        <td>ro</td>
    </tr>
    <tr>
        <td>loop blocks</td>j
        <td>while, for, until</td>j
        <td>rl</td>
    </tr>
    <tr>
        <td>control blocks</td>
        <td>do, begin, if, unless, case</td>
        <td>rc</td>
    </tr>
    <tr>
        <td>do statement</td>
        <td>do</td>
        <td>rd</td>
    </tr>
    <tr>
        <td>any block including above all</td>
        <td>all blocks</td>
        <td>rr</td>
    </tr>
</table>

**Comment by rhysd** [comment]
> it changes the current character.

Oh, really?  So the `r{character}` mappings may be broken...  I usually use this plugin with `g:textobje_ruby_more_mappings = 0`.  So I can't notice if they are broken.
