### ISSUE TITLE
[Feature Request] Block variable text object

### ISSUE THREAD

**Issue by NigoroJr** [rhysd/vim-textobj-ruby#4]
こんにちは。例えば次のようなスニペットがあった場合、

```ruby
arr.each_with_index do |elem, i|
  # stuff
end
```

`|elem, i|`の中で`ci|`としたときに(`ci]`と同じ感覚で)変数を選択できるテキストオブジェクトがあると便利だなぁと思ったのですが、このプラグインの趣旨と少しはずれてしまうでしょうか？

\# 英語のほうが良ければ変更します

**Comment by rhysd** [comment]
[vim-textobj-between](https://github.com/thinca/vim-textobj-between) はいかがでしょうか？ 特定の文字列で囲まれた範囲をテキストオブジェクトにしたいというのは Ruby に限った話ではないと思うので，こちらのほうが汎用性が高いと思います．

**Comment by NigoroJr** [comment]
おお！こんな便利なプラグインがあったとは。Rubyに関連するプラグインばかり検索していました。早速試してみたところ、まさに探していたものでした。ありがとうございます。
